keybindings:
    - modifier:
        - Ctrl
        - Alt
      key: UP_ARROW
      bindfeature: moveToTop
      
    - modifier:
        - Ctrl
        - Alt
      key: DOWN_ARROW
      bindfeature: moveToBottom
      
    - modifier:
        - Ctrl
        - Alt
      key: LEFT_ARROW
      bindfeature: moveToLeft
      
    - modifier:
        - Ctrl
        - Alt
      key: RIGHT_ARROW
      bindfeature: moveToRight
      
    - modifier:
        - Ctrl
        - Alt
      key: U
      bindfeature: moveToTopLeft
      
    - modifier:
        - Ctrl
        - Alt
      key: I
      bindfeature: moveToTopRight
      
    - modifier:
        - Ctrl
        - Alt
      key: J
      bindfeature: moveToBottomLeft
      
    - modifier:
        - Ctrl
        - Alt
      key: K
      bindfeature: moveToBottomRight

    - modifier:
        - Ctrl
        - Alt
      key: =
      bindfeature: makeLarger

    - modifier:
        - Ctrl
        - Alt
      key: "-"
      bindfeature: makeSmaller

    - modifier:
        - Ctrl
        - Alt
        - Shift
      key: UP_ARROW
      bindfeature: makeFullHeight

